#!/home/pkn/.local/share/virtualenvs/learning_python_hands_on-AqkO5Sk9/bin/python


### #!/usr/local/bin/python


print('The Bright Side ' + 'of Life...') # + means concatenate for strings



#why this is not used /home/pkn/.local/share/virtualenvs/learning_python_hands_on-AqkO5Sk9/bin/python
"""
❯ which python
/home/pkn/.local/share/virtualenvs/learning_python_hands_on-AqkO5Sk9/bin/python
❯ python part_1/chap_1/brian
The Bright Side of Life...
❯ python part_1/chap_1/brian
The Bright Side of Life...

"""